[general]
environment = "PRODUCTION"

[discord]
prefix        = "!"
token         = "<token>"
client_id     = 000000000000000000
client_secret = "<secret>"

[discord.webhooks]
guilds   = "<url>"
commands = "<url>"
errors   = "<url>"

[[discord.ext.lava.links]]
host     = "<ip>"
port     = 00000
password = "<password>"

[connections.postgresql]
dsn = "<dsn>"

[connections.redis]
dsn = "<dsn>"

[connections.spotify]
client_id     = "<id>"
client_secret = "<secret>"

[connections.uploader]
token = "<token>"
