[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name        = "CD-bot"
version     = "0.0.1"
description = "A general purpose music bot."
authors     = ["Axel <axelancerr@gmail.com>"]


[tool.poetry.dependencies]
python           = "^3.10.0"
async-timeout    = "~4.0.0"
asyncpg          = "~0.26.0"
colorama         = "~0.4.0"
colorthief       = "~0.2.0"
discord-ext-lava = "~0.5.0"
humanize         = "~4.4.0"
mystbin-py       = "~5.0.0"
pendulum         = "~2.1.0"
pillow           = "~9.2.0"
rapidfuzz        = "~2.10.0"
tornado          = "~6.2.0"
wand             = "~0.6.0"

aiohttp    = { version = "~3.8.0", extras = ["speedups"] }
discord-py = { version = "~2.0.0", extras = ["voice", "speed"] }
jishaku    = { version = "~2.5.0", extras = ["voice", "procinfo"] }
redis      = { version = "~4.3.0", extras = ["hiredis"] }


[tool.pyright]
include                = ["cd", "launcher.py", "config_example.py"]
pythonVersion          = "3.10"
typeCheckingMode       = "strict"
useLibraryCodeForTypes = true

reportPrivateUsage       = false
reportUnknownMemberType  = false
reportImportCycles       = false
reportMissingTypeStubs   = false
reportPrivateImportUsage = false
