[tool.poetry]
name = "CD-Bot"
version = "0.1.0"
description = "A general purpose music bot."
authors = ["Axel <axelancerr@gmail.com>"]
license = "MIT"


[tool.poetry.dependencies]
python = "~3.10.0"

aiohttp = "~3.7.4"
aioredis = "~2.0.1"
asyncpg = "~0.25.0"
humanize = "~3.13.1"
jishaku = "~2.3.2"
pendulum = "~2.1.2"
psutil = "~5.9.0"
pynacl = "~1.5.0"
rapidfuzz = "~1.9.1"
wheel = "^0.37.1"
"mystbin.py" = "~2.2.0"

slate = { git = "git@github.com:Axelware/slate", branch = "main" }
"pretty" = { git = "git@github.com:ShineyDev/pretty", branch = "main" }
"discord.py" = { git = "git@github.com:Rapptz/discord.py", branch = "master" }
"discord-ext-alternatives" = { git = "git@github.com:Ext-Creators/discord-ext-alternatives", rev = "2987112c31de9bada4ee95cee9007a326e496e19" }


[tool.poetry.dev-dependencies]
isort = "*"


[tool.isort]
line_length = 125
multi_line_output = 3
lines_after_imports = 2
combine_star = true
include_trailing_comma = true
star_first = true
known_local_folder = ["core", "extensions", "utilities", "typings"]
import_heading_future = "Future"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Packages"
import_heading_firstparty = "My stuff"
import_heading_localfolder = "My stuff"


[tool.pyright]
include = ["bot"]
verboseOutput = false
pythonVersion = "3.10"
typeCheckingMode = "basic"
useLibraryCodeForTypes = true

strictListInference = true
strictDictionaryInference = true
strictSetInference = true
reportMissingImports = false
reportPrivateImportUsage = false
